services:

#########################################################
# FastAPI
#########################################################

- type: web
  name: trade-risk-api

  env: docker

  dockerfilePath: ./Dockerfile

  dockerContext: .

  plan: free

  autoDeploy: true

#########################################################
# Prometheus
#########################################################

- type: web
  name: prometheus

  env: docker

  dockerfilePath: ./monitoring/prometheus/Dockerfile

  dockerContext: ./monitoring/prometheus

  plan: free

  autoDeploy: true

#########################################################
# Alertmanager
#########################################################

- type: web
  name: alertmanager

  env: docker

  dockerfilePath: ./monitoring/alertmanager/Dockerfile

  dockerContext: ./monitoring/alertmanager

  plan: free

  autoDeploy: true

#########################################################
# Grafana
#########################################################

- type: web
  name: grafana

  env: docker

  dockerfilePath: ./monitoring/grafana/Dockerfile

  dockerContext: ./monitoring/grafana

  plan: free

  autoDeploy: true