global:

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '22102a030104@gmail.com'
  smtp_auth_username: '22102a030104@gmail.com'
  smtp_auth_password: ${GMAIL_PASSWORD}
  smtp_require_tls: true

route:
  receiver: notifications

receivers:

  - name: notifications

    email_configs:

      - to: '22102a030104@gmail.com'

    telegram_configs:

      - bot_token: ${TELEGRAM_BOT_TOKEN}
        chat_id: ${TELEGRAM_CHAT_ID}
        send_resolved: true