global:

  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '22102a030104@gmail.com'
  smtp_auth_username: '22102a030104@gmail.com'
  smtp_auth_password: hnmb wlml jzmv wfcts
  smtp_require_tls: true

route:
  receiver: notifications

receivers:

  - name: notifications

    email_configs:

      - to: '22102a030104@gmail.com'

    telegram_configs:

      - bot_token: 8498082535:AAGkkGpHdzb3PNWcmLzp-aPQ7yN84AN0Lh4
        chat_id: 5360828542
        send_resolved: true